version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    ignore:
      - dependency-name: "vite"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@vitejs/plugin-vue"
        update-types:
          - "version-update:semver-major"
