version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    ignore:
      - dependency-name: "vite"
        versions:
          - ">=6"

      - dependency-name: "@vitejs/plugin-vue"
        versions:
          - ">=6"
