const servers = [
    {
        "ip": "62.113.206.102",
        "port": 22124,
        "country": "Germany",
        "maxclients": 14,
        "perm": 1,
        "name": "Directory Server",
        "ipaddrs": "",
        "city": "Frankfurt",
        "ping": 12,
        "nclients": 1,
        "os": "Linux",
        "version": "3.5.2git",
        "clients": [
            {
                "chanid": 0,
                "country": "United Kingdom",
                "instrument": "None",
                "skill": "Not Set",
                "ip": "31.50.251.192",
                "name": "",
                "city": ""
            }
        ]
    },
    {
        "ip": "104.231.45.240",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "Jethrine Machine",
        "ipaddrs": "",
        "city": "Lexington",
        "NAT": true,
        "ping": 111,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "51.158.106.80",
        "port": 22125,
        "country": "France",
        "maxclients": 20,
        "perm": 1,
        "name": "Jazz / Open Jam",
        "ipaddrs": "",
        "city": "Paris",
        "NAT": true,
        "ping": 20,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.1"
    },
    {
        "ip": "71.205.109.80",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "JamDen",
        "ipaddrs": "",
        "city": "Denver"
    },
    {
        "ip": "173.166.235.138",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "SacServer2",
        "ipaddrs": "",
        "city": "Sacramento",
        "NAT": true,
        "ping": 147,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "109.109.120.57",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "Jam at Ghrenbear's",
        "ipaddrs": "",
        "city": "Amsterdam",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.0git"
    },
    {
        "ip": "3.8.2.188",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "PocketOctopus",
        "ipaddrs": "",
        "city": "London",
        "ping": 2,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "80.193.74.242",
        "port": 13310,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "jamulus.dbs.isandt.n",
        "ipaddrs": "",
        "city": "Plymouth"
    },
    {
        "ip": "62.113.206.23",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "Bierimpuls",
        "ipaddrs": "",
        "city": "Frankfurt",
        "ping": 12,
        "nclients": 1,
        "os": "Linux",
        "version": "3.5.3git",
        "clients": [
            {
                "chanid": 0,
                "country": "Poland",
                "instrument": "Electric Guitar",
                "skill": "Not Set",
                "ip": "80.50.135.154",
                "name": "Dems ",
                "city": "Krakow"
            }
        ]
    },
    {
        "ip": "5.196.72.67",
        "port": 22124,
        "country": "France",
        "maxclients": 10,
        "perm": 1,
        "name": "hackerscardgame",
        "ipaddrs": "",
        "city": "Kimsufi",
        "ping": 9,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "185.73.44.67",
        "port": 22120,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "nylonmojo.uk",
        "ipaddrs": "",
        "city": "London",
        "ping": 1,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.5git"
    },
    {
        "ip": "109.116.37.95",
        "port": 22124,
        "country": "Italy",
        "maxclients": 8,
        "perm": 1,
        "name": "Roma Spinaceto H24",
        "ipaddrs": "",
        "city": "Rome",
        "NAT": true,
        "ping": 34,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.7git"
    },
    {
        "ip": "94.23.211.85",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4"
    },
    {
        "ip": "37.187.4.174",
        "port": 22124,
        "country": "France",
        "maxclients": 10,
        "perm": 1,
        "name": "ks3367473",
        "ipaddrs": "",
        "city": "",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "159.69.197.178",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 1,
        "name": "iodine",
        "ipaddrs": "",
        "city": "Nuremberg",
        "ping": 23,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "3.10.116.23",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "RhythmandFrames",
        "ipaddrs": "",
        "city": "London",
        "ping": 3,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.7git"
    },
    {
        "ip": "176.9.137.5",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 1,
        "name": "live.autistici.org",
        "ipaddrs": "",
        "city": "Frankfurt",
        "ping": 21,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.5git"
    },
    {
        "ip": "79.161.201.116",
        "port": 22124,
        "country": "Norway",
        "maxclients": 10,
        "perm": 1,
        "name": "JazzMainStream",
        "ipaddrs": "",
        "city": "Fredrikstad",
        "NAT": true,
        "ping": 36,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "81.174.155.168",
        "port": 54850,
        "country": "United Kingdom",
        "maxclients": 16,
        "perm": 1,
        "name": "jamulus.drealm.info",
        "ipaddrs": "",
        "city": "London",
        "ping": 9,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "93.176.166.2",
        "port": 22124,
        "country": "Kenya",
        "maxclients": 10,
        "perm": 1,
        "name": "Batucada",
        "ipaddrs": "",
        "city": "Alicante",
        "NAT": true,
        "ping": 49,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.5git"
    },
    {
        "ip": "95.216.147.49",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 1,
        "name": "faler-hel1-2",
        "ipaddrs": "",
        "city": "helsinki",
        "NAT": true,
        "ping": 36,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4cvs"
    },
    {
        "ip": "149.210.213.110",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 1,
        "name": "JAMshack",
        "ipaddrs": "",
        "city": "Amsterdam",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "35.176.100.229",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "BiddersServer",
        "ipaddrs": "",
        "city": "London",
        "ping": 2,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "35.178.169.223",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "Elevators",
        "ipaddrs": "",
        "city": "London",
        "ping": 2,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "37.235.116.58",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 1,
        "name": "WarrenWillisBand",
        "ipaddrs": "",
        "city": "Den Haag",
        "ping": 10,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4"
    },
    {
        "ip": "13.238.219.219",
        "port": 22124,
        "country": "Australia",
        "maxclients": 10,
        "perm": 1,
        "name": "BriansJamulusServer",
        "ipaddrs": "",
        "city": "Melbourne",
        "NAT": true,
        "ping": 266,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.5"
    },
    {
        "ip": "18.132.79.55",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "MelodyMaker",
        "ipaddrs": "",
        "city": "London",
        "ping": 3,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "31.170.123.77",
        "port": 28767,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 0,
        "name": "TMS",
        "ipaddrs": "",
        "city": "Maidstone",
        "ping": 3,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4"
    },
    {
        "ip": "93.55.226.36",
        "port": 22124,
        "country": "Italy",
        "maxclients": 8,
        "perm": 0,
        "name": "Open-Music",
        "ipaddrs": "",
        "city": "Milano",
        "ping": 22,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "51.158.106.80",
        "port": 22124,
        "country": "France",
        "maxclients": 20,
        "perm": 1,
        "name": "PetitesEcuries",
        "ipaddrs": "",
        "city": "Paris",
        "NAT": true,
        "ping": 20,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.1"
    },
    {
        "ip": "96.21.212.27",
        "port": 22124,
        "country": "Canada",
        "maxclients": 10,
        "perm": 1,
        "name": "BoumboyServer",
        "ipaddrs": "",
        "city": "Quebec",
        "NAT": true,
        "ping": 97,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.6"
    },
    {
        "ip": "35.177.105.144",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "duggysjamserver",
        "ipaddrs": "",
        "city": "london",
        "ping": 3,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.8git"
    },
    {
        "ip": "1.157.239.88",
        "port": 22124,
        "country": "Australia",
        "maxclients": 10,
        "perm": 1,
        "name": "CoogeeCampfirePublic",
        "ipaddrs": "",
        "city": "",
        "NAT": true
    },
    {
        "ip": "146.185.158.104",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 1,
        "name": "Anders",
        "ipaddrs": "",
        "city": "Amsterdam",
        "ping": 6,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "178.82.215.219",
        "port": 22124,
        "country": "Switzerland",
        "maxclients": 10,
        "perm": 0,
        "name": "server.home",
        "ipaddrs": "",
        "city": "Aarau",
        "NAT": true,
        "ping": 43,
        "nclients": 1,
        "os": "Linux",
        "version": "3.5.0git",
        "clients": [
            {
                "chanid": 1,
                "country": "Switzerland",
                "instrument": "Streamer",
                "skill": "Intermediate",
                "ip": "192.168.179.104",
                "name": "Landev/Streaming",
                "city": "Aarau"
            }
        ]
    },
    {
        "ip": "45.33.125.183",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "blasto",
        "ipaddrs": "",
        "city": "RichardsonTX",
        "NAT": true,
        "ping": 102,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4"
    },
    {
        "ip": "213.171.185.165",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "Seeweb-BandAtHome",
        "ipaddrs": "",
        "city": "Frosinone",
        "NAT": true,
        "ping": 30,
        "nclients": 2,
        "os": "Linux",
        "version": "3.5.3git",
        "clients": [
            {
                "chanid": 0,
                "country": "Italy",
                "instrument": "None",
                "skill": "Not Set",
                "ip": "93.42.104.18",
                "name": "",
                "city": ""
            },
            {
                "chanid": 2,
                "country": "Italy",
                "instrument": "Bass Guitar",
                "skill": "Not Set",
                "ip": "2.234.131.162",
                "name": "Pasquale ",
                "city": "padova"
            }
        ]
    },
    {
        "ip": "193.136.187.3",
        "port": 22124,
        "country": "Portugal",
        "maxclients": 10,
        "perm": 1,
        "name": "University Lusiada",
        "ipaddrs": "",
        "city": "Lisboa",
        "NAT": true,
        "ping": 59,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "86.13.250.177",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "PlumOcelot.uk",
        "ipaddrs": "",
        "city": "London",
        "NAT": true,
        "ping": 30,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.5"
    },
    {
        "ip": "84.198.32.116",
        "port": 22124,
        "country": "Belgium",
        "maxclients": 10,
        "perm": 1,
        "name": "Laurens Jam Box",
        "ipaddrs": "",
        "city": "Mechelen",
        "NAT": true,
        "ping": 37,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "35.176.99.205",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "NDY_and_friends",
        "ipaddrs": "",
        "city": "London",
        "ping": 3,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "87.106.204.116",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 1,
        "name": "JogiTec PA-Technik",
        "ipaddrs": "",
        "city": "Bad Honnef",
        "ping": 19,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "134.0.115.61",
        "port": 22124,
        "country": "Russia",
        "maxclients": 8,
        "perm": 1,
        "name": "Nibiru 2",
        "ipaddrs": "",
        "city": "Moscow",
        "NAT": true,
        "ping": 45,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "193.205.130.251",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "UnivPM-A3Lab",
        "ipaddrs": "",
        "city": "Ancona",
        "NAT": true,
        "ping": 38,
        "nclients": 1,
        "os": "Windows",
        "version": "3.4.4",
        "clients": [
            {
                "chanid": 0,
                "country": "Italy",
                "instrument": "None",
                "skill": "Not Set",
                "ip": "127.0.0.1",
                "name": "dummy-test",
                "city": "Ancona"
            }
        ]
    },
    {
        "ip": "80.96.234.254",
        "port": 5418,
        "country": "Romania",
        "maxclients": 8,
        "perm": 0,
        "name": "Sundance",
        "ipaddrs": "",
        "city": "Bucharest",
        "NAT": true,
        "ping": 42,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.3cvs"
    },
    {
        "ip": "18.156.87.179",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 1,
        "name": "MrMariusJamulus",
        "ipaddrs": "",
        "city": "Frankfurt",
        "ping": 14,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.5"
    },
    {
        "ip": "172.93.49.15",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "MaxtonServer",
        "ipaddrs": "",
        "city": "NYC",
        "NAT": true,
        "ping": 70,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4cvs"
    },
    {
        "ip": "82.65.64.61",
        "port": 22124,
        "country": "Germany",
        "maxclients": 40,
        "perm": 1,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 17,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "54.245.190.19",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "ZFJamulus",
        "ipaddrs": "",
        "city": "Hillsboro",
        "NAT": true,
        "ping": 161,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "35.181.155.36",
        "port": 32124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "JamCloud 2 (3.5.0) ",
        "ipaddrs": "",
        "city": "Paris",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.0"
    },
    {
        "ip": "185.233.107.140",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 1,
        "name": "CaptRauti-Rock-Jam",
        "ipaddrs": "",
        "city": "Soehlde",
        "ping": 17,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "96.224.215.107",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "JabaTaba",
        "ipaddrs": "",
        "city": "Long Island",
        "NAT": true,
        "ping": 78,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "35.197.197.151",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 20,
        "perm": 1,
        "name": "Google",
        "ipaddrs": "",
        "city": "GoogleDataCentre",
        "ping": 2,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "68.66.235.151",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "referralwx",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 129,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "80.127.152.29",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 0,
        "name": "banaan",
        "ipaddrs": "",
        "city": "Leiden",
        "ping": 10,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "138.197.188.9",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "achille-tra-le-nuvol",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 18,
        "nclients": 1,
        "os": "Linux",
        "version": "3.5.3git",
        "clients": [
            {
                "chanid": 0,
                "country": "Germany",
                "instrument": "Bass Guitar",
                "skill": "Not Set",
                "ip": "91.37.86.30",
                "name": "Florian",
                "city": ""
            }
        ]
    },
    {
        "ip": "45.124.53.21",
        "port": 22124,
        "country": "Australia",
        "maxclients": 10,
        "perm": 1,
        "name": "HobsonsOpenMic",
        "ipaddrs": "",
        "city": "Melbourne",
        "NAT": true,
        "ping": 316,
        "nclients": 3,
        "os": "Linux",
        "version": "3.5.2git",
        "clients": [
            {
                "chanid": 1,
                "country": "Singapore",
                "instrument": "None",
                "skill": "Beginner",
                "ip": "202.83.109.14",
                "name": "AP",
                "city": "Singapore"
            },
            {
                "chanid": 2,
                "country": "Australia",
                "instrument": "Acoustic Guitar",
                "skill": "Not Set",
                "ip": "115.70.114.134",
                "name": "Victor",
                "city": ""
            },
            {
                "chanid": 3,
                "country": "Australia",
                "instrument": "Electric Guitar",
                "skill": "Not Set",
                "ip": "101.175.197.254",
                "name": "Joezep",
                "city": "Riverina  NSW"
            }
        ]
    },
    {
        "ip": "35.181.155.36",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "JamCloud 3.5.0",
        "ipaddrs": "",
        "city": "Paris",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.0"
    },
    {
        "ip": "62.113.241.37",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 1,
        "name": "VIER|und|ICH|1",
        "ipaddrs": "",
        "city": "Frankfurt",
        "ping": 13,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.6git"
    },
    {
        "ip": "146.247.49.117",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "ManxJam",
        "ipaddrs": "",
        "city": "IsleofMan",
        "ping": 12,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "185.73.44.58",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "pHreak",
        "ipaddrs": "",
        "city": "London",
        "ping": 1,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.1"
    },
    {
        "ip": "82.64.200.55",
        "port": 22124,
        "country": "France",
        "maxclients": 5,
        "perm": 1,
        "name": "Gronazulus",
        "ipaddrs": "",
        "city": "Coarraze",
        "NAT": true,
        "ping": 67,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.7git"
    },
    {
        "ip": "83.136.106.123",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 12,
        "perm": 1,
        "name": "FortePrenestino",
        "ipaddrs": "",
        "city": "Universe",
        "ping": 28,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4"
    },
    {
        "ip": "159.213.83.61",
        "port": 7320,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "jamulus",
        "ipaddrs": "",
        "city": ""
    },
    {
        "ip": "54.252.172.166",
        "port": 22124,
        "country": "Australia",
        "maxclients": 10,
        "perm": 1,
        "name": "AU_OPEN_JAMULUS",
        "ipaddrs": "",
        "city": "Australia",
        "NAT": true,
        "ping": 271,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.6git"
    },
    {
        "ip": "62.113.206.92",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 1,
        "name": "* CORONA PARTY *",
        "ipaddrs": "",
        "city": "Frankfurt",
        "ping": 12,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "82.163.78.21",
        "port": 22120,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "mojolounge.net",
        "ipaddrs": "",
        "city": "London",
        "ping": 1,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4cvs"
    },
    {
        "ip": "2.7.201.124",
        "port": 22124,
        "country": "France",
        "maxclients": 10,
        "perm": 1,
        "name": "CactusTherapie",
        "ipaddrs": "",
        "city": "Chambery",
        "ping": 25,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "77.166.76.148",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 1,
        "name": "olgaspij",
        "ipaddrs": "",
        "city": "gasselte",
        "ping": 17,
        "nclients": 1,
        "os": "Windows",
        "version": "3.5.2",
        "clients": [
            {
                "chanid": 0,
                "country": "Netherlands",
                "instrument": "None",
                "skill": "Not Set",
                "ip": "192.168.2.177",
                "name": "olga",
                "city": ""
            }
        ]
    },
    {
        "ip": "51.38.237.171",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 1,
        "name": "Cool Element",
        "ipaddrs": "",
        "city": "Groningen",
        "ping": 9,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4"
    },
    {
        "ip": "3.224.179.186",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "JapaneseKaraokeUSA",
        "ipaddrs": "",
        "city": "Massachusetts",
        "NAT": true,
        "ping": 75,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "18.132.112.66",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "MvLKorenServer",
        "ipaddrs": "",
        "city": "London",
        "ping": 2,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "80.221.56.97",
        "port": 1024,
        "country": "Finland",
        "maxclients": 16,
        "perm": 1,
        "name": "Hop mode",
        "ipaddrs": "",
        "city": "Helsinki"
    },
    {
        "ip": "99.88.45.102",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "wastedyears",
        "ipaddrs": "",
        "city": "Alameda",
        "NAT": true,
        "ping": 150,
        "nclients": 0,
        "os": "MacOS",
        "version": "3.4.5"
    },
    {
        "ip": "91.192.190.6",
        "port": 22124,
        "country": "Russia",
        "maxclients": 10,
        "perm": 1,
        "name": "Nibiru 1",
        "ipaddrs": "",
        "city": "Saint Petersburg",
        "NAT": true,
        "ping": 50,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "173.212.232.221",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 29,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "51.210.8.130",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "Standard Jazz Band",
        "ipaddrs": "",
        "city": "France",
        "NAT": true,
        "ping": 18,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "3.10.235.91",
        "port": 22122,
        "country": "United Kingdom",
        "maxclients": 20,
        "perm": 1,
        "name": "RockLounge",
        "ipaddrs": "",
        "city": "London",
        "ping": 2,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "158.140.192.27",
        "port": 36019,
        "country": "Australia",
        "maxclients": 10,
        "perm": 1,
        "name": "Andrew",
        "ipaddrs": "",
        "city": "Longreach"
    },
    {
        "ip": "68.82.103.240",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "eCompositor",
        "ipaddrs": "",
        "city": "Yardley, PA",
        "NAT": true,
        "ping": 88,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.6"
    },
    {
        "ip": "108.16.122.79",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "BluesberryJam",
        "ipaddrs": "",
        "city": "Philadelphia",
        "NAT": true,
        "ping": 88,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "92.223.109.13",
        "port": 22124,
        "country": "Russia",
        "maxclients": 10,
        "perm": 1,
        "name": "jam.sibecodome.org",
        "ipaddrs": "",
        "city": "Novosibirsk",
        "NAT": true,
        "ping": 82,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "173.180.83.66",
        "port": 22124,
        "country": "Canada",
        "maxclients": 10,
        "perm": 1,
        "name": "VanRays",
        "ipaddrs": "",
        "city": "Coquitlam",
        "NAT": true,
        "ping": 140,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "192.227.107.145",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "JapaneseKaraoke",
        "ipaddrs": "",
        "city": "Boston,MA",
        "NAT": true,
        "ping": 69,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "51.254.138.225",
        "port": 22124,
        "country": "France",
        "maxclients": 10,
        "perm": 1,
        "name": "Quebreizh",
        "ipaddrs": "",
        "city": "Dineault",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "74.194.137.126",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "debian",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 122,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "136.144.201.239",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 1,
        "name": "jamulus.ddq.nl",
        "ipaddrs": "",
        "city": "Valkenburg",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "35.177.77.117",
        "port": 1237,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "jamminthejazz",
        "ipaddrs": "",
        "city": "Winchester",
        "ping": 2,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "213.64.180.134",
        "port": 2586,
        "country": "Sweden",
        "maxclients": 16,
        "perm": 1,
        "name": "meet.repet.se",
        "ipaddrs": "",
        "city": "Stockholm"
    },
    {
        "ip": "213.64.180.134",
        "port": 21639,
        "country": "Sweden",
        "maxclients": 16,
        "perm": 1,
        "name": "meet-at-repet-se",
        "ipaddrs": "",
        "city": "Stockholm"
    },
    {
        "ip": "71.174.57.53",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 85,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "81.110.1.210",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "KItchenCollaborative",
        "ipaddrs": "",
        "city": "Soton",
        "NAT": true,
        "ping": 15,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4"
    },
    {
        "ip": "64.19.74.40",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "North Country Jammer",
        "ipaddrs": "",
        "city": "Crown Point",
        "NAT": true,
        "ping": 78,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.1"
    },
    {
        "ip": "178.222.218.217",
        "port": 1024,
        "country": "Serbia",
        "maxclients": 10,
        "perm": 1,
        "name": "nohoup",
        "ipaddrs": "",
        "city": "sombor",
        "NAT": true,
        "ping": 37,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "109.180.85.176",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "Nashville",
        "ipaddrs": "",
        "city": "Huddersfield",
        "ping": 11,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "94.61.22.3",
        "port": 1248,
        "country": "Portugal",
        "maxclients": 15,
        "perm": 1,
        "name": "Snayler's Rpi4",
        "ipaddrs": "",
        "city": "Coimbra",
        "NAT": true,
        "ping": 42,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "94.61.22.3",
        "port": 1192,
        "country": "Portugal",
        "maxclients": 15,
        "perm": 1,
        "name": "Snayler's Jam",
        "ipaddrs": "",
        "city": "Coimbra",
        "NAT": true,
        "ping": 43,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "76.187.60.243",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "Midnight Rodeo Band",
        "ipaddrs": "",
        "city": "Dallas",
        "NAT": true,
        "ping": 118,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "95.131.147.7",
        "port": 22124,
        "country": "Russia",
        "maxclients": 10,
        "perm": 1,
        "name": "MyTestServer",
        "ipaddrs": "",
        "city": "BP2"
    },
    {
        "ip": "149.210.223.223",
        "port": 22134,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "Letsdens",
        "ipaddrs": "",
        "city": "Amsterdam",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "82.59.194.156",
        "port": 53604,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "Max cerca Band",
        "ipaddrs": "",
        "city": "Rome",
        "NAT": true,
        "ping": 39,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "79.230.164.119",
        "port": 22124,
        "country": "Congo Kinshasa",
        "maxclients": 10,
        "perm": 1,
        "name": "vorodyn.de",
        "ipaddrs": "",
        "city": "Aachen",
        "NAT": true,
        "ping": 28,
        "nclients": 1,
        "os": "Linux",
        "version": "3.4.3",
        "clients": [
            {
                "chanid": 0,
                "country": "Germany",
                "instrument": "Listener",
                "skill": "Beginner",
                "ip": "79.230.163.160",
                "name": "Petra away",
                "city": "Aachen"
            }
        ]
    },
    {
        "ip": "121.45.187.215",
        "port": 22124,
        "country": "Australia",
        "maxclients": 10,
        "perm": 1,
        "name": "tassie",
        "ipaddrs": "",
        "city": "launceston"
    },
    {
        "ip": "52.221.206.21",
        "port": 22134,
        "country": "Singapore",
        "maxclients": 10,
        "perm": 1,
        "name": "SOFTJAM",
        "ipaddrs": "",
        "city": "Singapore",
        "NAT": true,
        "ping": 172,
        "nclients": 1,
        "os": "Linux",
        "version": "3.5.3git",
        "clients": [
            {
                "chanid": 0,
                "country": "Australia",
                "instrument": "None",
                "skill": "Not Set",
                "ip": "203.220.176.245",
                "name": "",
                "city": ""
            }
        ]
    },
    {
        "ip": "92.2.160.19",
        "port": 22144,
        "country": "United Kingdom",
        "maxclients": 4,
        "perm": 1,
        "name": "alw_Audio",
        "ipaddrs": "",
        "city": "Sevenoaks",
        "ping": 7,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "76.70.40.134",
        "port": 22124,
        "country": "Canada",
        "maxclients": 10,
        "perm": 1,
        "name": "Ottawa Music",
        "ipaddrs": "",
        "city": "Ottawa",
        "NAT": true,
        "ping": 81,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "62.113.206.102",
        "port": 11111,
        "country": "Germany",
        "maxclients": 6,
        "perm": 1,
        "name": "centest",
        "ipaddrs": "",
        "city": "Oberrad",
        "ping": 13,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2git"
    },
    {
        "ip": "83.32.24.21",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 34,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4"
    },
    {
        "ip": "90.127.98.97",
        "port": 22124,
        "country": "France",
        "maxclients": 9,
        "perm": 1,
        "name": "Jam Jazz Lvc",
        "ipaddrs": "",
        "city": "Louveciennes",
        "ping": 11,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4"
    },
    {
        "ip": "125.236.201.44",
        "port": 22124,
        "country": "New Zealand",
        "maxclients": 10,
        "perm": 1,
        "name": "Sancta Maria",
        "ipaddrs": "",
        "city": "Auckland",
        "NAT": true,
        "ping": 273,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "82.69.27.64",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 16,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "18.139.225.89",
        "port": 22134,
        "country": "El Salvador",
        "maxclients": 10,
        "perm": 1,
        "name": "TheBigBreakSGJamulus",
        "ipaddrs": "",
        "city": "Singapore",
        "NAT": true,
        "ping": 177,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "106.69.125.112",
        "port": 22124,
        "country": "Australia",
        "maxclients": 10,
        "perm": 1,
        "name": "barbeQSteve",
        "ipaddrs": "",
        "city": "sydney",
        "NAT": true,
        "ping": 290,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "109.109.120.66",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "Jam at Ak's",
        "ipaddrs": "",
        "city": "Amsterdam",
        "ping": 8,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.0git"
    },
    {
        "ip": "15.161.104.129",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "Jam-Milano",
        "ipaddrs": "",
        "city": "Milan",
        "NAT": true,
        "ping": 23,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "35.246.97.220",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 50,
        "perm": 1,
        "name": "JazzLounge",
        "ipaddrs": "",
        "city": "GoogleGCPLondon",
        "ping": 1,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "93.42.255.109",
        "port": 59138,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "LaSamba",
        "ipaddrs": "",
        "city": "Milan",
        "NAT": true,
        "ping": 40,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.4cvs"
    },
    {
        "ip": "18.132.2.185",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "CampfireServer",
        "ipaddrs": "",
        "city": "London",
        "ping": 2,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "3.248.89.217",
        "port": 22124,
        "country": "Ireland",
        "maxclients": 20,
        "perm": 1,
        "name": "Kildare Choral",
        "ipaddrs": "",
        "city": "Dublin",
        "ping": 12,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.2"
    },
    {
        "ip": "84.108.124.163",
        "port": 22124,
        "country": "Israel",
        "maxclients": 10,
        "perm": 1,
        "name": "A123",
        "ipaddrs": "",
        "city": "Ben Ami",
        "NAT": true,
        "ping": 74,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.6"
    },
    {
        "ip": "73.83.106.174",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "SW",
        "ipaddrs": "",
        "city": "North Bend",
        "NAT": true,
        "ping": 161,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "118.93.53.151",
        "port": 22124,
        "country": "New Zealand",
        "maxclients": 10,
        "perm": 1,
        "name": "Auckland Live",
        "ipaddrs": "",
        "city": "Auckland",
        "NAT": true,
        "ping": 257,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.1"
    },
    {
        "ip": "68.71.244.132",
        "port": 22124,
        "country": "Canada",
        "maxclients": 10,
        "perm": 1,
        "name": "liveatthewick",
        "ipaddrs": "",
        "city": "London, ON",
        "NAT": true
    },
    {
        "ip": "162.199.38.196",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "Flight",
        "ipaddrs": "",
        "city": "Waukesha",
        "NAT": true,
        "ping": 118,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "82.38.118.192",
        "port": 1024,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "Soukous Party 2",
        "ipaddrs": "",
        "city": "ristol",
        "NAT": true,
        "ping": 26,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "79.145.215.75",
        "port": 22124,
        "country": "Spain",
        "maxclients": 10,
        "perm": 1,
        "name": "TEST_RPI3B+",
        "ipaddrs": "",
        "city": "Valladolid"
    },
    {
        "ip": "2.239.100.5",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "RockinXRoma noJazz",
        "ipaddrs": "",
        "city": "Roma",
        "NAT": true,
        "ping": 30,
        "nclients": 1,
        "os": "Windows",
        "version": "3.5.2",
        "clients": [
            {
                "chanid": 0,
                "country": "Italy",
                "instrument": "Bass Guitar",
                "skill": "Not Set",
                "ip": "192.168.1.81",
                "name": "RockinXRoma",
                "city": "Roma"
            }
        ]
    },
    {
        "ip": "80.15.161.102",
        "port": 22124,
        "country": "France",
        "maxclients": 10,
        "perm": 0,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "ping": 11,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "62.11.160.90",
        "port": 22124,
        "country": "Italy",
        "maxclients": 6,
        "perm": 0,
        "name": "SupportiMusicaliJam",
        "ipaddrs": "",
        "city": "Torino",
        "NAT": true,
        "ping": 28,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "92.169.0.118",
        "port": 22124,
        "country": "France",
        "maxclients": 10,
        "perm": 0,
        "name": "BluegrassParis",
        "ipaddrs": "",
        "city": "Paris",
        "ping": 13,
        "nclients": 1,
        "os": "Windows",
        "version": "3.5.2",
        "clients": [
            {
                "chanid": 0,
                "country": "France",
                "instrument": "Acoustic Guitar",
                "skill": "Intermediate",
                "ip": "192.168.1.16",
                "name": "Tareguy",
                "city": "Palaiseau"
            }
        ]
    },
    {
        "ip": "107.3.1.148",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "JamulusCoopulus",
        "ipaddrs": "",
        "city": "SoBurlington",
        "ping": 98,
        "nclients": 0,
        "os": "Linux",
        "version": "3.4.8git"
    },
    {
        "ip": "84.83.101.102",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 0,
        "name": "vandergrinten",
        "ipaddrs": "",
        "city": "Amsterdam",
        "ping": 9,
        "nclients": 0,
        "os": "MacOS",
        "version": "3.5.2"
    },
    {
        "ip": "24.207.92.35",
        "port": 22124,
        "country": "Canada",
        "maxclients": 10,
        "perm": 1,
        "name": "crossroads",
        "ipaddrs": "",
        "city": "Delta",
        "NAT": true,
        "ping": 156,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "185.98.164.12",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "Eterno's Kitchen",
        "ipaddrs": "",
        "city": "Rome "
    },
    {
        "ip": "78.228.116.175",
        "port": 2162,
        "country": "France",
        "maxclients": 10,
        "perm": 1,
        "name": "Les Copains",
        "ipaddrs": "",
        "city": "Seine et Marne"
    },
    {
        "ip": "121.74.34.151",
        "port": 22124,
        "country": "New Zealand",
        "maxclients": 10,
        "perm": 0,
        "name": "Stomp",
        "ipaddrs": "",
        "city": "Wellington",
        "NAT": true,
        "ping": 274,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "93.36.187.104",
        "port": 38931,
        "country": "Italy",
        "maxclients": 10,
        "perm": 0,
        "name": "ACHE SONERO ",
        "ipaddrs": "",
        "city": "BERGAMO",
        "NAT": true,
        "ping": 35,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "5.102.5.161",
        "port": 58049,
        "country": "Italy",
        "maxclients": 10,
        "perm": 0,
        "name": "trio_test",
        "ipaddrs": "",
        "city": "Trento",
        "NAT": true
    },
    {
        "ip": "174.20.60.108",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 0,
        "name": "Szaszka",
        "ipaddrs": "",
        "city": "Minneapolis, MN",
        "NAT": true,
        "ping": 120,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "172.117.200.157",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "GWK Jamulus Server",
        "ipaddrs": "",
        "city": "Los Angeles",
        "NAT": true,
        "ping": 150,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "178.221.132.233",
        "port": 1024,
        "country": "Serbia",
        "maxclients": 10,
        "perm": 0,
        "name": "houp",
        "ipaddrs": "",
        "city": "sombor",
        "NAT": true,
        "ping": 36,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.1"
    },
    {
        "ip": "80.122.44.138",
        "port": 22124,
        "country": "Austria",
        "maxclients": 10,
        "perm": 0,
        "name": "jam2night.at",
        "ipaddrs": "",
        "city": "Upper Austria",
        "NAT": true,
        "ping": 33,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "83.87.93.80",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 0,
        "name": "Q Online",
        "ipaddrs": "",
        "city": "Hilversum",
        "ping": 34,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "92.34.244.168",
        "port": 22124,
        "country": "Sweden",
        "maxclients": 50,
        "perm": 0,
        "name": "Wessling",
        "ipaddrs": "",
        "city": "Uppsala",
        "NAT": true
    },
    {
        "ip": "92.202.239.138",
        "port": 22124,
        "country": "Japan",
        "maxclients": 10,
        "perm": 0,
        "name": "Sanbi no Heya",
        "ipaddrs": "",
        "city": "Tokyo",
        "NAT": true,
        "ping": 232,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "95.62.158.229",
        "port": 22124,
        "country": "Spain",
        "maxclients": 10,
        "perm": 0,
        "name": "Wooky",
        "ipaddrs": "",
        "city": "Sevilla"
    },
    {
        "ip": "71.206.46.128",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "OnceRevealed",
        "ipaddrs": "",
        "city": "FrederickMD"
    },
    {
        "ip": "95.118.70.73",
        "port": 22124,
        "country": "Any Country",
        "maxclients": 10,
        "perm": 1,
        "name": "grungejam",
        "ipaddrs": "",
        "city": "München",
        "NAT": true,
        "ping": 30,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "79.255.74.190",
        "port": 22124,
        "country": "Germany",
        "maxclients": 13,
        "perm": 1,
        "name": "DUD-Sessions",
        "ipaddrs": "",
        "city": "Duderstadt",
        "ping": 21,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "3.15.141.150",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 0,
        "name": "MLLServer",
        "ipaddrs": "",
        "city": "UnitedStates",
        "NAT": true,
        "ping": 97,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "194.26.174.60",
        "port": 22124,
        "country": "Spain",
        "maxclients": 10,
        "perm": 0,
        "name": "Local",
        "ipaddrs": "",
        "city": "Vidreresi",
        "NAT": true,
        "ping": 49,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.1"
    },
    {
        "ip": "208.114.92.22",
        "port": 41297,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "NAT": true
    },
    {
        "ip": "174.18.32.40",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "Cactus Jam",
        "ipaddrs": "",
        "city": "Tucson, AZ",
        "NAT": true,
        "ping": 164,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.6"
    },
    {
        "ip": "98.210.136.24",
        "port": 22124,
        "country": "United States",
        "maxclients": 10,
        "perm": 0,
        "name": "alameda-jam",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 160,
        "nclients": 0,
        "os": "Linux",
        "version": "3.5.3git"
    },
    {
        "ip": "91.242.153.122",
        "port": 4963,
        "country": "Spain",
        "maxclients": 10,
        "perm": 0,
        "name": "manuelheavy",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 45,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "93.35.189.38",
        "port": 30303,
        "country": "Italy",
        "maxclients": 10,
        "perm": 0,
        "name": "Towering flowers",
        "ipaddrs": "",
        "city": "Rome",
        "NAT": true,
        "ping": 38,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "213.10.161.67",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 0,
        "name": "R.P.S. Guitar/Vocals",
        "ipaddrs": "",
        "city": "Den Haag",
        "ping": 17,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.1"
    },
    {
        "ip": "92.57.239.91",
        "port": 22124,
        "country": "Spain",
        "maxclients": 10,
        "perm": 0,
        "name": "kuer",
        "ipaddrs": "",
        "city": "arevalo",
        "NAT": true,
        "ping": 32,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.1"
    },
    {
        "ip": "37.142.6.121",
        "port": 39020,
        "country": "Israel",
        "maxclients": 10,
        "perm": 1,
        "name": "shirly weissmann",
        "ipaddrs": "",
        "city": "Haifa",
        "NAT": true,
        "ping": 90,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "95.91.238.57",
        "port": 20236,
        "country": "Germany",
        "maxclients": 10,
        "perm": 0,
        "name": "billydah",
        "ipaddrs": "",
        "city": "Dachau",
        "NAT": true,
        "ping": 30,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "81.0.0.78",
        "port": 21183,
        "country": "Spain",
        "maxclients": 10,
        "perm": 0,
        "name": "AlfRivas",
        "ipaddrs": "",
        "city": "Rivas",
        "NAT": true,
        "ping": 66,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "91.53.86.100",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 0,
        "name": "GW",
        "ipaddrs": "",
        "city": "Hamburg"
    },
    {
        "ip": "93.223.144.205",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 0,
        "name": "AcousticProbe privat",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 42,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "37.14.87.193",
        "port": 22124,
        "country": "Spain",
        "maxclients": 10,
        "perm": 0,
        "name": "Combo Dive Privado",
        "ipaddrs": "",
        "city": "Sant Feliu",
        "NAT": true,
        "ping": 32,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "93.37.134.23",
        "port": 7100,
        "country": "Italy",
        "maxclients": 10,
        "perm": 0,
        "name": "server EM",
        "ipaddrs": "",
        "city": "Roma"
    },
    {
        "ip": "176.246.20.247",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 0,
        "name": "testmolfetta",
        "ipaddrs": "",
        "city": "Molfetta",
        "NAT": true
    },
    {
        "ip": "185.176.244.70",
        "port": 33982,
        "country": "Norway",
        "maxclients": 10,
        "perm": 0,
        "name": "Hardkor",
        "ipaddrs": "",
        "city": "Oslo",
        "NAT": true
    },
    {
        "ip": "92.167.84.207",
        "port": 22124,
        "country": "France",
        "maxclients": 10,
        "perm": 0,
        "name": "Didier",
        "ipaddrs": "",
        "city": "Castelnau le lez",
        "ping": 26,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "213.37.70.196",
        "port": 22124,
        "country": "Spain",
        "maxclients": 10,
        "perm": 0,
        "name": "Acordes",
        "ipaddrs": "",
        "city": "Madrid",
        "NAT": true,
        "ping": 38,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "82.253.31.68",
        "port": 22124,
        "country": "France",
        "maxclients": 10,
        "perm": 1,
        "name": "cho cho ostico",
        "ipaddrs": "",
        "city": "Paris",
        "ping": 21,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "89.151.47.59",
        "port": 30478,
        "country": "Poland",
        "maxclients": 10,
        "perm": 0,
        "name": "Voyo",
        "ipaddrs": "",
        "city": "Katowice",
        "NAT": true,
        "ping": 44,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "90.112.60.47",
        "port": 1026,
        "country": "France",
        "maxclients": 10,
        "perm": 0,
        "name": "Jouer!",
        "ipaddrs": "",
        "city": "Revel"
    },
    {
        "ip": "82.58.224.34",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 0,
        "name": "Luca Schiavon public",
        "ipaddrs": "",
        "city": "verona",
        "NAT": true,
        "ping": 36,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.7"
    },
    {
        "ip": "185.247.48.3",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 0,
        "name": "Zandbak",
        "ipaddrs": "",
        "city": "Stiphout",
        "ping": 12,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "81.44.203.200",
        "port": 22124,
        "country": "Spain",
        "maxclients": 10,
        "perm": 1,
        "name": "CMG",
        "ipaddrs": "",
        "city": "COLLADO VILLALBA",
        "NAT": true,
        "ping": 38,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "185.211.163.35",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "BigFabio",
        "ipaddrs": "",
        "city": "Capena - Roma"
    },
    {
        "ip": "2.44.62.131",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "TDJ",
        "ipaddrs": "",
        "city": "Mantova",
        "NAT": true,
        "ping": 39,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "151.24.85.136",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 0,
        "name": "Alessio",
        "ipaddrs": "",
        "city": "Rome"
    },
    {
        "ip": "84.166.227.172",
        "port": 22124,
        "country": "Germany",
        "maxclients": 10,
        "perm": 0,
        "name": "Brosi",
        "ipaddrs": "",
        "city": "Harz",
        "ping": 24,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.5"
    },
    {
        "ip": "83.84.168.48",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 1,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "ping": 19,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "2.25.85.134",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 0,
        "name": "Scott",
        "ipaddrs": "",
        "city": "Lewes",
        "NAT": true,
        "ping": 20,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.7"
    },
    {
        "ip": "84.120.222.101",
        "port": 22124,
        "country": "Spain",
        "maxclients": 10,
        "perm": 0,
        "name": "Rockarg",
        "ipaddrs": "",
        "city": "Palma"
    },
    {
        "ip": "92.20.242.45",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 1,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "ping": 7,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "5.94.5.134",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 0,
        "name": "ivano tolotti",
        "ipaddrs": "",
        "city": "colverde ",
        "NAT": true,
        "ping": 82,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.2"
    },
    {
        "ip": "200.57.117.105",
        "port": 39373,
        "country": "Mexico",
        "maxclients": 10,
        "perm": 1,
        "name": "Delta",
        "ipaddrs": "",
        "city": "CDMX"
    },
    {
        "ip": "86.132.150.77",
        "port": 22124,
        "country": "United Kingdom",
        "maxclients": 10,
        "perm": 0,
        "name": "THS - Private",
        "ipaddrs": "",
        "city": "London",
        "ping": 6,
        "nclients": 1,
        "os": "MacOS",
        "version": "3.5.2",
        "clients": [
            {
                "chanid": 0,
                "country": "United Kingdom",
                "instrument": "Electric Guitar",
                "skill": "Intermediate",
                "ip": "192.168.1.134",
                "name": "Rodders",
                "city": "LONDON"
            }
        ]
    },
    {
        "ip": "5.55.113.16",
        "port": 22124,
        "country": "Greece",
        "maxclients": 10,
        "perm": 0,
        "name": "The Dropout",
        "ipaddrs": "",
        "city": "Attica",
        "NAT": true,
        "ping": 66,
        "nclients": 2,
        "os": "Windows",
        "version": "3.5.2",
        "clients": [
            {
                "chanid": 0,
                "country": "Greece",
                "instrument": "Electric Guitar",
                "skill": "Intermediate",
                "ip": "192.168.2.6",
                "name": "Dropout peter",
                "city": "Athens"
            },
            {
                "chanid": 1,
                "country": "Greece",
                "instrument": "Bass Guitar",
                "skill": "Expert",
                "ip": "91.140.89.147",
                "name": "Dropout Johnnie",
                "city": "Athens"
            }
        ]
    },
    {
        "ip": "82.57.149.152",
        "port": 55883,
        "country": "Italy",
        "maxclients": 10,
        "perm": 0,
        "name": "Mr1",
        "ipaddrs": "",
        "city": "Roma"
    },
    {
        "ip": "62.46.198.176",
        "port": 62823,
        "country": "Austria",
        "maxclients": 10,
        "perm": 0,
        "name": "SteamCo",
        "ipaddrs": "",
        "city": "Vienna",
        "NAT": true,
        "ping": 31,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "91.168.128.216",
        "port": 59162,
        "country": "France",
        "maxclients": 10,
        "perm": 0,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 17,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.1"
    },
    {
        "ip": "91.166.173.45",
        "port": 58628,
        "country": "France",
        "maxclients": 10,
        "perm": 0,
        "name": "",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 24,
        "nclients": 0,
        "os": "Windows",
        "version": "3.5.2"
    },
    {
        "ip": "213.147.154.25",
        "port": 22124,
        "country": "Spain",
        "maxclients": 10,
        "perm": 1,
        "name": "oscarcabron",
        "ipaddrs": "",
        "city": "palma",
        "NAT": true,
        "ping": 75,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "95.92.137.207",
        "port": 22124,
        "country": "Portugal",
        "maxclients": 10,
        "perm": 0,
        "name": "Kolme",
        "ipaddrs": "",
        "city": "Lisbon",
        "NAT": true,
        "ping": 44,
        "nclients": 0,
        "os": "MacOS",
        "version": "3.5.2"
    },
    {
        "ip": "83.81.203.159",
        "port": 22124,
        "country": "Netherlands",
        "maxclients": 10,
        "perm": 0,
        "name": "The Young Ones",
        "ipaddrs": "",
        "city": "Alphen aan den Rijn",
        "ping": 20,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.4"
    },
    {
        "ip": "31.27.207.110",
        "port": 22124,
        "country": "Italy",
        "maxclients": 10,
        "perm": 1,
        "name": "The Canteeners",
        "ipaddrs": "",
        "city": "Roma",
        "NAT": true,
        "ping": 36,
        "nclients": 0,
        "os": "Windows",
        "version": "3.4.7"
    },
    {
        "ip": "39.96.175.236",
        "port": 22124,
        "country": "China",
        "maxclients": 50,
        "perm": 0,
        "name": "Jamulus Server China",
        "ipaddrs": "",
        "city": "",
        "NAT": true,
        "ping": 0,
        "nclients": 2
    },
    {
        "ip": "129.41.87.3",
        "port": 33417,
        "country": "United States",
        "maxclients": 10,
        "perm": 1,
        "name": "cmcJamulus",
        "ipaddrs": "",
        "city": "Pittsburgh"
    },
    {
        "ip": "85.226.180.109",
        "port": 22124,
        "country": "Sweden",
        "maxclients": 10,
        "perm": 0,
        "name": "johans Jam",
        "ipaddrs": "",
        "city": "",
        "NAT": true
    },
    {
        "ip": "89.115.168.79",
        "port": 22124,
        "country": "Portugal",
        "maxclients": 3,
        "perm": 0,
        "name": "2M3TPrivate",
        "ipaddrs": "",
        "city": "Sacavém",
        "NAT": true,
        "ping": 43,
        "nclients": 2,
        "os": "MacOS",
        "version": "3.4.7",
        "clients": [
            {
                "chanid": 0,
                "country": "Portugal",
                "instrument": "Keyboard",
                "skill": "Expert",
                "ip": "178.166.55.180",
                "name": "rui2mt",
                "city": ""
            },
            {
                "chanid": 2,
                "country": "Portugal",
                "instrument": "Keyboard",
                "skill": "Expert",
                "ip": "127.0.0.1",
                "name": "joaogo2m3t",
                "city": "Sacavém"
            }
        ]
    },
    {
        "ip": "188.147.158.145",
        "port": 37849,
        "country": "Poland",
        "maxclients": 10,
        "perm": 1,
        "name": "Franek ",
        "ipaddrs": "",
        "city": "Nysa",
        "NAT": true
    }
]

export default servers
